[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "xemu-dev-pgraph"
version = "0.1.0"
description = "Headless PGRAPH regression test runner and diff report generator for xemu"
readme = "README.md"
requires-python = ">=3.12"
license = "unlicense"
authors = [
    { name = "Erik Abair" }
]
dependencies = [
    "nxdk-pgraph-test-runner>=0.1.24",
    "nxdk-pgraph-test-repacker>=0.1.0",
    "requests~=2.33.1",
    "GitPython~=3.1.44",
    "Jinja2~=3.1.5",
    "frozendict~=2.4.6",
]

[project.scripts]
xemu-pgraph-run = "xemu_dev_pgraph.runner:main"
xemu-pgraph-diff = "xemu_dev_pgraph.pipeline:main"
xemu-pgraph-merge = "xemu_dev_pgraph.runner:merge_main"
xemu-pgraph-hw-diff = "xemu_dev_pgraph.hw_diffs:main"
xemu-pgraph-xemu-diff = "xemu_dev_pgraph.xemu_diffs:main"
xemu-pgraph-site = "xemu_dev_pgraph.site_generator:main"

[tool.setuptools.packages.find]
include = ["xemu_dev_pgraph*"]

[tool.setuptools.package-data]
"xemu_dev_pgraph" = ["templates/*", "templates/**/*"]

[tool.hatch.envs.types]
type = "virtual"
path = ".venv-mypy"
extra-dependencies = [
  "pip",
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:xemu_dev_pgraph}"

[tool.mypy]
disable_error_code = ["import-untyped", "import-not-found"]
